from __future__ import annotations

import seared as s
from doc.models import Demo
from seared.doc import document


class TestDocument:
    def setup_method(self):
        self.md = document(Demo)

    def test_title_and_docstring(self):
        assert self.md.startswith('# Demo\n')
        assert 'A demo model.' in self.md
        assert 'Second paragraph.' in self.md

    def test_fields_table_header(self):
        assert '| field | wire key | type | required | default | notes |' in self.md

    def test_pipe_in_type_is_escaped(self):
        # `str | None` must be escaped so the table column count survives.
        assert r'`str \| None`' in self.md
        assert '`str | None`' not in self.md

    def test_pipe_in_doc_is_escaped(self):
        assert r'origin \| system' in self.md

    def test_nested_link(self):
        assert '[`Inner`](Inner.md)' in self.md

    def test_dump_false_note(self):
        assert 'not emitted (`dump=False`)' in self.md

    def test_enum_section(self):
        assert '## Enumerations' in self.md
        assert '### `band` → `Band`' in self.md
        assert '| `UHF` | `0` |' in self.md

    def test_variants_section(self):
        assert '## Variants' in self.md
        assert 'Envelope: flat.' in self.md
        assert '[`StartCmd`](StartCmd.md)' in self.md

    def test_footer(self):
        assert self.md.rstrip().endswith('_Generated by `seared.doc` — do not edit by hand._')

    def test_custom_link_resolver(self):
        md = document(Demo, link_for=lambda c: f'schemas/{c.__name__}.md')
        assert '[`Inner`](schemas/Inner.md)' in md


class TestPlainClass:
    def test_no_enum_or_variant_sections_when_absent(self):
        @s.seared
        class Flat(s.Seared):
            """Flat."""

            a: int = s.Int(default=1)

        md = document(Flat)
        assert '## Enumerations' not in md
        assert '## Variants' not in md
        assert '## Fields' in md
