"""Markdown rendering for :class:`SchemaDoc`.

Built from small section functions (``render_header`` / ``render_fields_table``
/ ``render_enums`` / ``render_variants``) so other renderers — notably zeared's
wire-aware one — can recompose them around their own sections. ``document()``
assembles the core (Message-agnostic) page.
"""
from __future__ import annotations

from typing import Callable

from .introspect import SchemaDoc, introspect

LinkFor = Callable[[type], str]


def _default_link(cls: type) -> str:
    return f'{cls.__name__}.md'


def _pipe(text: str) -> str:
    """Escape ``|`` so it survives a Markdown table cell (even inside code)."""
    return text.replace('|', r'\|')


def _cell(text: str | None) -> str:
    """Escape a value for a Markdown table cell."""
    if not text:
        return ''
    return _pipe(text.replace('\n', ' ')).strip()


def render_header(schema: SchemaDoc) -> str:
    out = [f'# {schema.name}']
    if schema.doc:
        out.append('')
        out.append(schema.doc)
    return '\n'.join(out)


def render_fields_table(schema: SchemaDoc, link_for: LinkFor = _default_link) -> str:
    if not schema.fields:
        return ''
    rows = [
        '## Fields',
        '',
        '| field | wire key | type | required | default | notes |',
        '|-------|----------|------|----------|---------|-------|',
    ]
    for f in schema.fields:
        type_cell = f'`{_pipe(f.type_str)}`'
        if f.nested is not None:
            type_cell = f'[`{_pipe(f.type_str)}`]({link_for(f.nested)})'
        notes = []
        if f.doc:
            notes.append(_cell(f.doc))
        if not f.dump:
            notes.append('not emitted (`dump=False`)')
        rows.append(
            f'| `{f.attr}` '
            f'| {("`" + f.wire_key + "`") if f.wire_key else "—"} '
            f'| {type_cell} '
            f'| {"✓" if f.required else ""} '
            f'| {_pipe(f.default_repr)} '
            f'| {" · ".join(notes)} |'
        )
    return '\n'.join(rows)


def render_enums(schema: SchemaDoc) -> str:
    enum_fields = [f for f in schema.fields if f.enum is not None]
    if not enum_fields:
        return ''
    out = ['## Enumerations']
    for f in enum_fields:
        assert f.enum is not None
        out += ['', f'### `{f.attr}` → `{f.enum.name}`', '',
                '| member | wire value |', '|--------|------------|']
        for name, value in f.enum.members:
            out.append(f'| `{name}` | `{_pipe(repr(value))}` |')
    return '\n'.join(out)


def render_variants(schema: SchemaDoc, link_for: LinkFor = _default_link) -> str:
    union_fields = [f for f in schema.fields if f.variants is not None]
    if not union_fields:
        return ''
    out = ['## Variants']
    for f in union_fields:
        assert f.variants is not None
        out += ['', f'### `{f.attr}`', '', f'Envelope: {f.envelope}.']
        if f.fallback is not None:
            out.append(f'Unknown tags fall back to `{f.fallback.__name__}`.')
        out += ['', '| tag | class |', '|-----|-------|']
        for v in f.variants:
            out.append(f'| `{v.tag}` | [`{v.cls.__name__}`]({link_for(v.cls)}) |')
    return '\n'.join(out)


def document(cls: type, *, link_for: LinkFor = _default_link) -> str:
    """Render the full core Markdown page for a ``@seared`` class."""
    schema = introspect(cls)
    return render_schema(schema, link_for=link_for)


def render_schema(schema: SchemaDoc, *, link_for: LinkFor = _default_link) -> str:
    """Assemble a core page from an already-introspected :class:`SchemaDoc`."""
    sections = [
        render_header(schema),
        render_fields_table(schema, link_for),
        render_enums(schema),
        render_variants(schema, link_for),
        '_Generated by `seared.doc` — do not edit by hand._',
    ]
    body = '\n\n'.join(s for s in sections if s)
    return body + '\n'
